### PR TITLE
Added PromotionsPage.html for feature/issue#5 and Updated CSS

### PR DESCRIPTION
**Pull request by abid-dhariwal**

### CODE REVIEW

**Review by ahtishamMa — DISMISSED** [review]
reviewed

**Review by jawadc1 — DISMISSED** [review]
REVIEWED

**Review by NoumanParvaiz — DISMISSED** [review]
Reviewed

**Review by jawadc1 — APPROVED** [review]
REVIEWED

**Review by ahtishamMa — APPROVED** [review]
Reviewed

**Review by NoumanParvaiz — APPROVED** [review]
Conflicts resolved

**Pull request merged**
