### PR TITLE
Testing Complete

### PR DESCRIPTION
**Pull request by sagheriqbal57**
This pull request aims to merge the changes from the release/sprint-1 branch into the main branch. The release/sprint-1 branch contains the following updates and features that have been thoroughly tested and debugged:

Implementation of the Home page

Implementation of the Products page

Implementation of the Product Details page

Implementation of the Contact Us page

Implementation of the Promotions page

Shared CSS file for consistent styling across all HTML pages

Bug fixes and performance improvements

Reviewers:
All team members are requested to review the changes and provide their feedback. We need a total of 4 approving reviews to proceed with the merge.

Testing:
The release/sprint-1 branch has been tested for functionality, responsiveness, and cross-browser compatibility. No major issues were found during testing.

### CODE REVIEW

**Review by jawadc1 — APPROVED** [review]
REVIEWED

**Review by NoumanParvaiz — APPROVED** [review]
Great work, team! I have thoroughly reviewed the changes in the release/sprint-1 branch and tested the functionality of all pages.

**Review by ahtishamMa — APPROVED** [review]
Reviewed

**Review by abid-dhariwal — APPROVED** [review]
reviewed

**Pull request merged**
