### PR TITLE
Added Home Page for feature/issue#1 & Updated Css for Home Page styling

### PR DESCRIPTION
**Pull request by sagheriqbal57**

### CODE REVIEW

**Review by ahtishamMa — DISMISSED** [review]
reviewed

**Review by abid-dhariwal — DISMISSED** [review]
reviewed

**Review by NoumanParvaiz — DISMISSED** [review]
reviewed

**Review by jawadc1 — DISMISSED** [review]
REVIEWED

**Review by jawadc1 — APPROVED** [review]
REVIEWED

**Review by jawadc1 — APPROVED** [review]
REVIEWED

**Review by ahtishamMa — APPROVED** [review]
Reviewed

**Review by NoumanParvaiz — APPROVED** [review]
conflict resolved

**Review by abid-dhariwal — APPROVED** [review]
conflict resolved

**Pull request merged**
